dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
dotenv: .env
networks:
  default: development
  development:
    verify: False
  rinkeby:
    verify: False
  polygon-test:
    verify: False
  polygon-main:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}